export enum MatchEventType {
    BUILDING_KILL = "BUILDING_KILL",
    CHAMPION_KILL = "CHAMPION_KILL",
    ELITE_MONSTER_KILL = "ELITE_MONSTER_KILL",
    ITEM_DESTROYED = "ITEM_DESTROYED",
    ITEM_PURCHASED = "ITEM_PURCHASED",
    ITEM_SOLD = "ITEM_SOLD",
    ITEM_UNDO = "ITEM_UNDO",
    SKILL_LEVEL_UP = "SKILL_LEVEL_UP",
    WARD_KILL = "WARD_KILL",
    WARD_PLACED = "WARD_PLACED",

    // Custom games
    CAPTURE_POINT = "CAPTURE_POINT",
    ASCENDED_EVENT = "ASCENDED_EVENT",
    PORO_KING_SUMMON = "PORO_KING_SUMMON",
}